### ISSUE TITLE
Placement of BNO055 is disadvantageous regarding accelerometer usage

### ISSUE THREAD

**Issue by DaRaiden** [generationmake/JECCbot_mini#1]
The current placement of the BNO055 module is disadvantageous regarding accelerometer usage.

While rotating the measured acceleration at the current position does not match the expected acceleration of the robot assuming the robots coordinate system's origin is located at the center between the motors on the motor axis. This fact makes useful sensor fusion for motion tracking/recording more difficult.

See https://blog.nxp.com/tech-insights/accelerometer-placement-where-and-why for detailed explanations.

**Comment by generationmake** [comment]
This issue should be fixed with release v0.3

There are now mounting holes in the center between the motors. The BNO055 can be mounted in the center between the axles with distance bolts.
